---
samples: sample.tsv

units: units.tsv

# files and directories
#fastq_dir: "fastq/"
working_dir: "temp/"
result_dir: "results/"
annotation: "annotation/"

#Parameters for the rules
GENOME_ZIP_FASTA_URL: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M20/GRCm38.primary_assembly.genome.fa.gz
GENOME_ZIP_GTF_URL: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M20/gencode.vM20.annotation.gtf.gz
#ENCODE repeat_masker
REPEAT_GTF_URL: http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/GRCm38_Ensembl_rmsk_TE.gtf.gz
REPEAT_LOCIND: http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/mm10_rmsk_TE.gtf.locInd.gz #others prebuilt indices can be found: http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/

#FASTP

# read quality trimming
fastp:
  qualified_quality_phred: 30 # Phred+33 score (> 15 for Proton Ion, > 30 or more for Illumina) 

## Genomic references, annotations and aligner indexes
refs:
  genome_url:  "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M17/GRCm38.primary_assembly.genome.fa.gz"
  gff_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M17/gencode.vM17.annotation.gff3.gz"

#"ftp://ftp.solgenomics.net/tomato_genome/annotation/ITAG3.2_release/ITAG3.2_gene_models.gff"
# Bowtie2 commands
#bowtie2 --end-to-end --very-sensitive -p 16 -q --mm -x ../../bowtie/hg19 -1 02_trimmed/filename_forward_trimmed.fastq -2 02_trimmed/filename_reverse_trimmed.fastq -U 02_trimmed/filename__forward_Unpaired_trimmed.fastq,02_trimmed/Hfilename_reverse_Unpaired_trimmed.fastq -S 03_bowtie/filename.sam

# Parameters for Bowtie2
bowtie2:
  params:
    mode: "--local"
    sensitivity: "--very-sensitive-local"
    verbose: "-q"

#BAMCOVERAGE

bamcoverage:
  binsize:                '10'
  normalizeUsing:         'RPKM'
  effectiveGenomeSize:    '2652783500'            #https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
  smoothLength:           '50'
